// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4IiPHMPVzaF5eEfJ4Do4Ek8sdvzcHB0A',
    appId: '1:111971339059:web:43952d842e22f1bd97cc46',
    messagingSenderId: '111971339059',
    projectId: 'fir-test-10ae1',
    authDomain: 'fir-test-10ae1.firebaseapp.com',
    storageBucket: 'fir-test-10ae1.appspot.com',
    measurementId: 'G-FPPLVYM6WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQjcVvr7dmNuGsCKkxqrCfwkoxo1ffYU',
    appId: '1:111971339059:android:af98133d7c61da3597cc46',
    messagingSenderId: '111971339059',
    projectId: 'fir-test-10ae1',
    storageBucket: 'fir-test-10ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxMEGKecszQ6HFFVJDCoAOM5WDtVl-QVA',
    appId: '1:111971339059:ios:6f36ddb19ef24aa497cc46',
    messagingSenderId: '111971339059',
    projectId: 'fir-test-10ae1',
    storageBucket: 'fir-test-10ae1.appspot.com',
    iosClientId: '111971339059-s2ov7ig78o8ok33q39j33ncbf0qn7kij.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbApp',
  );
}
